name: Workspace CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: workspace-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workspace:
    name: Workspace
    uses: themoretheless/.github/.github/workflows/rust-ci.yml@6f88a5d9f0e953894ff6a2f779fb05ebec9f6c4e # v1
    with:
      rust_toolchain: beta
      clippy_args: --locked --workspace --all-targets --all-features
      build_args: --locked --workspace --all-targets --all-features
      test_args: --locked --workspace --all-targets --all-features
      run_docs: true
      doc_args: --locked --no-deps --all-features
      run_package: true
      package_args: --locked
